220 Bug: Translated footer is static and timestamp has another format
mowi12/bierpongregeln pull request #222
Opened 2024-12-10 10:05 UTC by mowi12

See description of linked issue.

2025-02-01 13:40 UTC, Slartibartfass2 requested changes
Looks fine so far. I had some problems after rebasing.

2025-02-01 13:40 UTC, Slartibartfass2 commented on package.json
> +        "write-translations": "python3 update-footer-en.py",
You moved it to `scripts`, now you have to update this command too.

2025-02-01 20:31 UTC, mowi12 commented on package.json
> +        "write-translations": "python3 update-footer-en.py",
You're right, i will change it!

2025-02-20 10:24 UTC, Slartibartfass2 approved these changes

2025-02-20 10:25 UTC, merged