Feat/36 feature ruleset update
mowi12/bierpongregeln pull request #37
Opened 2023-09-07 19:08 UTC by mowi12

Closes #36

2023-09-10 19:33 UTC, Slartibartfass2 requested changes
LGTM!

2023-09-10 19:33 UTC, Slartibartfass2 commented on docs/regelwerk.mdx
> +3. Ein Ball zählt als Aufsetzer und somit als zwei Treffer, sobald er mindestens einmal auf dem Tisch aufgesetzt hat.
1. and 3. are very similar and can be combined imo.

e. g.
"Ein Ball, welcher mindestens einmal auf dem Tisch aufgesetzt hat und in einem Becher landet, zählt als Aufsetzer und somit als zwei Treffer."

2023-09-10 19:33 UTC, Slartibartfass2 commented on docs/regelwerk.mdx
> +5. Ein Rollender Ball darf nicht abgewehrt werden, ausser er hat vorher aufgesetzt und zählt somit als Aufsetzer.
```suggestion
5. Ein rollender Ball darf nicht abgewehrt werden, außer er hat vorher aufgesetzt und zählt somit als Aufsetzer.
```

2023-09-11 09:25 UTC, mowi12 reviewed
LGTM

2023-09-11 09:31 UTC, merged